### ISSUE TITLE
Can't upload cover art for episodes

### ISSUE THREAD

**Issue by AdrianFahrbach** [mauricerenck/kirby-podcaster#19]
There is no way to set the episode cover art in the panel if it wasn't already set in the mp3 metadata. I can only select uploaded files, not upload any new files.

**Comment by mauricerenck** [comment]
I always thought about the podcast-episodes tab from podcaster as an extention of a page blueprint which already has a files section. But you're right, that might not always be the case, I'll see where to add a files section.

Beside that, you should only upload a cover art image per episode if it's really necessary, apple recommends to do this in your mp3 metadata, not in your feed.
