### ISSUE TITLE
Missing language tag in RSS feed

### ISSUE THREAD

**Issue by AdrianFahrbach** [mauricerenck/kirby-podcaster#20]
The [iTunes Podcast Validator](https://podcastsconnect.apple.com/my-podcasts/new-feed) can't find a language tag. The language entry says: 

> **ITC.PodcastsConnect.language.null**

![Bildschirmfoto 2019-05-15 um 10 51 06](https://user-images.githubusercontent.com/45072099/57762207-5d908080-76ff-11e9-8b18-b9b86f20658b.png)

**Comment by mauricerenck** [comment]
I just looked into your feed (url from the screenshot) and saw you wrote `Deutsch` as language. Please use a valid language code, this could be `de` or `de-DE`.

see:

- https://github.com/simplepie/simplepie-ng/wiki/Spec:-iTunes-Podcast-RSS
- http://www.lingoes.net/en/translator/langcode.htm

**Comment by mauricerenck** [comment]
while checking your feed, I also saw your server doesn't support byte-range request, which is needed for streaming mp3, you can check that here: https://podba.se/validate/
