### ISSUE TITLE
"Class 'GetId3\GetId3Core' not found" when uploading audio file

### ISSUE THREAD

**Issue by AdrianFahrbach** [mauricerenck/kirby-podcaster#26]
Whenever I upload an audio file I get
`Class 'GetId3\GetId3Core' not found`
This error was already occurring in earlier versions of this plugin, I just ignored it until now.

My guess is that it's released to the mp3scan symlink, because I'm not able to upload or create symlinks on my server. I tried working around that problem by creating a symlink with php, but that didn't fix the GetId3 error:
`<?php
$target = 'vendor/wapmorgan/mp3info/bin/mp3scan';
$link = 'vendor/bin/mp3scan';
symlink($target, $link);
echo readlink($link);
?>`

**Comment by mauricerenck** [comment]
Thank you for letting me know. I changed the lib for all the id3 stuff. Please see the latest release (v1.1.2). Let me know it works for you now.

**Comment by AdrianFahrbach** [comment]
Thanks for your fast reply, really appreciate it!

Now it says:
`Class 'getID3' not found`

I have to include that I didn't install podcaster the recommended way, because I only have access to our FTP on the weekends. If you think that the problem is related to that, I can try installing it through the CLI on Monday.

What I did is install it locally using composer and then transfer my local files to our FTP. As far as I know it should work that way, but my composer knowledge is quite limited.

<img width="489" alt="Bildschirmfoto 2019-06-29 um 18 31 15" src="https://user-images.githubusercontent.com/45072099/60386917-2d792300-9a9c-11e9-80c8-2a3d9af6b409.png">

In addition to that, it still gives me a "phpunit" symlink error when uploading through FTP. I guess that thats not related to this problem, but maybe you should consider removing that one from the releases too, just to make the whole experience a bit smoother.

**Comment by mauricerenck** [comment]
I fear that is some composer autoload dependency stuff going wrong. I just released a new version (1.1.3) with another kind of composer/vendor setup. I just downloaded the zip via the link you can find in the readme and dropped the kirby-podcaster folder into the plugin folder. I was then able to work with it and also upload files without warning.

**Comment by AdrianFahrbach** [comment]
I'm not getting any errors now and the track length is automatically added in the panel, therefore I guess it's working.

Just dropping the kirby-podcaster folder in my plugins folder didn't work though and threw this error again:
`Class 'GetId3\GetId3Core' not found`
To get it working, I ran composer locally first and then uploaded the kirby-podcaster folder including its vendor folder.

I still got a symlink error from phpunit while uploading tough, so if possible, you should probably consider adding them to dev-dependencies.

**Comment by mauricerenck** [comment]
Strange, all the needed vendor files should be in the zip you download. Did you name the folder `kirby-podcaster`?

When running composer without any option, it also installs all the developer dependencies like phpunit, which you don't need on your site. That's where the symlink is comming from.

**Comment by AdrianFahrbach** [comment]
> Strange, all the needed vendor files should be in the zip you download.
They are in the last few releases. Maybe I just overlooked the folder, however, it seems to be a mistake on my part.

> Did you name the folder kirby-podcaster?
I always named it podcaster.
