### ISSUE TITLE
Podlove player doesn't work properly

### ISSUE THREAD

**Issue by joranovski** [mauricerenck/kirby-podcaster#38]
I'm working on local host

The error message I posted has not been seen again, but the issue I have is that the podloveplayer is not rendered. The HTML5 audio player is rendered.

I Inspect the DOM and I can see the js for the podlove player is inserted but it's not visible

![Schermafbeelding 2019-11-11 om 21 54 37](https://user-images.githubusercontent.com/504660/68620576-0dd41b80-04ce-11ea-8fd1-8c5a4d7e4150.png)

If you need info, please ask!

**Comment by mauricerenck** [comment]
Are there any errors in the console?

**Comment by joranovski** [comment]
@mauricerenck  there was this following error:

SyntaxError: '' string literal contains an unescaped line break
Caused bij linebreaks in the wysiwyg description textarea. 
By removing the linebreaks in the wysiwyg, the podloverplayer showed up!

**Comment by mauricerenck** [comment]
Thanks for letting me know! I will reopen this, because the plugin should handle linebreaks, so the player won't break.
