### ISSUE TITLE
PHP Deprecated: Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by felixhaeberle** [mauricerenck/kirby-podcaster#42]
With Kirby V3 and PHP v7.4.1:

`Deprecated: Array and string offset access syntax with curly braces is deprecated in /Users/felixhaberle/Sites/format-plus/website/site/plugins/podcaster/lib/PiwikTracker.php on line 476`

I think this can be fixed with  changing `$domain{$dl}` to `$domain[$dl]`. Thank you!

**Comment by mauricerenck** [comment]
Sorry for the late reply to this :/ 
Please update to the latest version, which will include the new matomo composer package, solving this issue.
