### ISSUE TITLE
Call to a member function query() on null

### ISSUE THREAD

**Issue by maxhoffmann** [mauricerenck/kirby-podcaster#68]
Hey there,

I’ve tried to set up the podcaster plugin on my server after successfully installing it locally. But whenever I enable the sqlite statistics I receive the following error, opening the website:

```
Call to a member function query() on null.
```

![Kirby CMS Debugger](https://github.com/mauricerenck/kirby-podcaster/assets/1227441/68f4251e-d5b1-492f-895c-78900ee4c010)

Any idea what might cause the issue?

**Comment by maxhoffmann** [comment]
Some additional info: it doesn’t seem to to create the `podcaster.sqlite` file on the server, although it doesn’t throw an error when line 18 or 19 is called

**Comment by mauricerenck** [comment]
Hey, seems like it cannot cannot connect 🤔  can you post your plugin configuration here, at least the stats part?

**Comment by maxhoffmann** [comment]
@mauricerenck I got it working. Looks like the server was a missing the sqlite extension for php or my permissions weren’t correctly set up. but I think it was the missing extension
