### ISSUE TITLE
[Feature Request] Make the podcast cover image optional

### ISSUE THREAD

**Issue by maxhoffmann** [mauricerenck/kirby-podcaster#69]
Currently the poster cover image of the podcast is not required in the panel, but not adding an image breaks the Podlove player snippet.

I’d suggest to keep the poster image optional and fix the code that generates the JSON config for the Podlove player. It can be configured to work without an image.

![Screenshot 2024-03-01 at 23 29 25](https://github.com/mauricerenck/kirby-podcaster/assets/1227441/02236df3-c81a-43bb-b3db-9b7a6e23aa8d)

**Comment by mauricerenck** [comment]
Thank you for letting me know. I guess I'll have to change it to a required field. I think platforms like apple require a cover image when submitting a new podcast. So I guess this is the better choice then.
