### ISSUE TITLE
Umlaute in chapter titles are displayed as encoded characters

### ISSUE THREAD

**Issue by maxhoffmann** [mauricerenck/kirby-podcaster#71]
Currently using Umlaute in chapter titles show up as encoded characters. The reasons for this seems to be that the titles are passed into `Xml::encode`, which is a security measurement. I wonder if there is a similar function in kirby that keeps the security but allows using Umlaute to fix this issue?

**Comment by mauricerenck** [comment]
This should be fixed in the latest release
