### ISSUE TITLE
feedRSS - Wrong date format with config intl date handler

### ISSUE THREAD

**Issue by batgithub** [mauricerenck/kirby-podcaster#72]
Thanks for your plugin, it's really great 🙂

I created a podcast in french, on my website. I did config kirby `date.handler` with `intl` to have date in french.
But it create wrong date in the RSS feed : `91, 31 3 2024 0::` instead of `Sun, 31 Mar 2024 00:00:00 +0100`.

**Comment by batgithub** [comment]
I did a quick fix with :

`<?=$feed->xmlTag('pubDate', $episode->date()->toDate(new \IntlDateFormatter('en', pattern: 'E, MMM YYYY HH:mm:ss zz')));?>`
In snippets/itemp.php

and 
`<lastBuildDate><?= \Kirby\Toolkit\Str::date($page->modified(), new \IntlDateFormatter('en', pattern: 'E, MMM YYYY HH:mm:ss zz'), 'en');?></lastBuildDate>`
in templates/podcasterfeed.php

I think it will be more resilient to precise the format in English on the rss feed.

**Comment by batgithub** [comment]
After bugs with spotify I finally found the right format : 
```
    <?=$feed->xmlTag('pubDate', $episode->date()->toDate(new \IntlDateFormatter('en_US',
    \IntlDateFormatter::FULL,
    \IntlDateFormatter::FULL,
    'UTC',
    \IntlDateFormatter::GREGORIAN,
    "EEE, dd MMM yyyy HH:mm:ss 'GMT'")));?>
    ```

**Comment by mauricerenck** [comment]
Thank you for the contribution and sorry for the very late reply, I was so busy my other plugins that I procrastinated around this issue. It'll be fixed in the upcoming release.
